apiVersion: v1
kind: ReplicationController
metadata:
  name: influxdb-v4
  namespace: kube-system
  labels: 
    k8s-app: influxdb
    version: v4
    kubernetes.io/cluster-service: "true"
spec: 
  replicas: 1
  selector: 
    k8s-app: influxdb
    version: v4
  template: 
    metadata: 
      labels: 
        k8s-app: influxdb
        version: v4
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: registry.h3cpaas.com/google_containers/heapster_influxdb:v0.7
          name: influxdb
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          ports: 
            - containerPort: 8083
            - containerPort: 8086
          volumeMounts:
          - name: influxdb-persistent-storage
            mountPath: /data
      volumes:
      - name: influxdb-persistent-storage
        emptyDir: {}

