apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns-autoscaler
  namespace: kube-system
  labels:
    k8s-app: kube-dns-autoscaler
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-dns-autoscaler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: "default"
      containers:
      - name: autoscaler
        image: registry.h3cpaas.com/google_containers/cluster-proportional-autoscaler-amd64:v1.1.1
        resources:
            requests:
                cpu: "20m"
                memory: "10Mi"
        command:
          - /cluster-proportional-autoscaler
          - --namespace=kube-system
          - --configmap=kube-dns-autoscaler
          - --target=ReplicationController/kube-dns-v20
          - --default-params={"linear":{"coresPerReplica":2,"nodesPerReplica":1,"min":1,"max":16,"preventSinglePointFailure":true}}
          - --logtostderr=true
          - --v=2
