kind: Service
apiVersion: v1
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Alertmanager"
spec: 
  ports: 
    - port: 9093
      targetPort: 9093
  selector: 
    k8s-app: alertmanager
    version: v0.5.1
    kubernetes.io/cluster-service: "true"
