apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: elasticsearch-discovery
  labels:
    plugin: elasticsearch-logging  
    component: elasticsearch
    role: master
spec:
  selector:
    plugin: elasticsearch-logging  
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
