apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: es-master
  namespace: kube-system
  labels:
    plugin: elasticsearch-logging  
    component: elasticsearch
    role: master
spec:
  selector:
    matchLabels:
      plugin: elasticsearch-logging    
      component: elasticsearch
      role: master
  template:
    metadata:
      labels:
        plugin: elasticsearch-logging      
        component: elasticsearch
        role: master
    spec:
      serviceAccount: elasticsearch-logging
      nodeSelector:
        "kube-system/es-node": "true"
      tolerations:
      - effect: NoSchedule
        key: node-role.tenxcloud.com/es
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: 10.5.79.237/system_containers/docker-elasticsearch-kubernetes:5.6.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "es-cluster"
        - name: "NUMBER_OF_MASTERS"
          value: "4"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"          
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms4g -Xmx4g -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
        - name: "storage"
          hostPath:
            path: /nas/es_master
