apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager-v0.5.1
  namespace: kube-system
  labels:
    k8s-app: alertmanager
    kubernetes.io/cluster-service: "true"
    version: v0.5.1
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: alertmanager
      version: v0.5.1
  template:
    metadata:
      labels:
        k8s-app: alertmanager
        version: v0.5.1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: registry.h3cpaas.com/prometheus/alertmanager:v0.5.1
          name: alertmanager
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 9093
