apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system
  labels: 
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Grafana"
spec:
  # On production clusters, consider setting up auth for grafana, and
  # exposing Grafana either using a LoadBalancer or a public IP.
  # type: LoadBalancer
  ports: 
    - port: 3000
      targetPort: 3000
  selector: 
    k8s-app: prometheusGrafana
    version: v4
    kubernetes.io/cluster-service: "true"

